## Lowest level config defaults for the common role

# used in winchester.yaml
config_path: 
    - /etc/stv3

# used in logging.conf
root_log_level: DEBUG
yagi_log_level: DEBUG
winchester_log_level: DEBUG
amqp_log_level: WARNING

# "level = INFO" logs SQL queries.
# "level = DEBUG" logs SQL queries and results.
# "level = WARNING" logs neither. Recommended for production systems
sqlalchemy_log_level: WARNING

database_url: mysql://winchester:testpasswd@localhost/winchester

statistics_period: 10
pipeline_worker_batch_size: 1000
pipeline_worker_delay: 10

#stackdistiller_plugins:
#   - my_plugin_1
#   - my_plugin_2

catch_all_notifications: false

pipeline_handlers:
    logger: winchester.pipeline_handler:LoggingHandler
    usage: winchester.pipeline_handler:UsageHandler
